### ISSUE TITLE
Suggestions are not ordered by penalty value

### ISSUE THREAD

**Issue by hrzafer** [ahmetaa/leblebi#1]
I added a new near key map for Turkish Characters:

```
static {
        TURKISH_DEASCIIFY_KEY_MAP.put('ç', "c");
        TURKISH_DEASCIIFY_KEY_MAP.put('ı', "i");
        TURKISH_DEASCIIFY_KEY_MAP.put('i', "ı");
        TURKISH_DEASCIIFY_KEY_MAP.put('ğ', "g");
        TURKISH_DEASCIIFY_KEY_MAP.put('ö', "o");
        TURKISH_DEASCIIFY_KEY_MAP.put('ş', "s");
        TURKISH_DEASCIIFY_KEY_MAP.put('ü', "u");
    }

final SingleWordSpellChecker spellChecker = new SingleWordSpellChecker(1, SingleWordSpellChecker.TURKISH_DEASCIIFY_KEY_MAP);
```

When I get suggestions for the "takim", it returns "tahkim". However the penalty for takım is only 0.5 and it should have been suggested, I suppose? Here are the full suggestions with penalties:

```
tahkim: 1.0
takip: 1.0
hakim: 1.0
taksim: 1.0
takım: 0.5
takdim: 1.0
takvim: 1.0
```

As a work around:

```
DoubleValueSet res = spellChecker.decode(word);
List> entryList = res.getAsEntryList();
Collections.sort(entryList);
```

**Comment by ahmetaa** [comment]
Yes I am aware of this. DoubleValueSet iterator is not sorted. A method that just turns the sorted String could work. I may discard using DoubleValueSet too.

**Comment by ahmetaa** [comment]
Using ascii-turkish maps like this is clever but IMO it is not the best way. I should make some changes to handle that functionality.

**Comment by ahmetaa** [comment]
This is fixed now.

**Comment by hrzafer** [comment]
Thanks
